# Generated by Django 4.1.6 on 2023-02-08 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_number_of_trades', models.PositiveIntegerField(default=0)),
                ('total_number_of_winning_trades', models.PositiveIntegerField(default=0)),
                ('total_number_of_losing_trades', models.PositiveIntegerField(default=0)),
                ('total_number_of_be_trade', models.PositiveIntegerField(default=0)),
                ('largest_winning_trade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('largest_losing_trade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_winning_trade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_losing_trade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_trade_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_profit_loss_per_trade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('return_of_investment', models.CharField(default='0%', max_length=200)),
                ('average_risk_reward', models.CharField(default='1:1', max_length=200)),
                ('average_risk_per_trade', models.CharField(default='0%', max_length=200)),
                ('average_reward_per_trade', models.CharField(default='0%', max_length=200)),
                ('trade_win_rate', models.CharField(default='0%', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', '-activate_date'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('market', models.CharField(default='EURUSD', max_length=200)),
                ('closed_position', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_price', models.FloatField(default=0)),
                ('stop_loss_price', models.FloatField(default=0)),
                ('take_profit_price', models.FloatField(blank=True, null=True)),
                ('actual_exit_price', models.FloatField(default=0)),
                ('risk_reward', models.CharField(blank=True, max_length=200, null=True)),
                ('screen_before', models.URLField(blank=True, null=True)),
                ('screen_after', models.URLField(blank=True, null=True)),
                ('trade_notes', models.TextField(blank=True, null=True)),
                ('discipline_rating', models.IntegerField(blank=True, null=True)),
                ('emotional_state_of_mind', models.TextField(blank=True, null=True)),
                ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.summary')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['created'],
            },
        ),
    ]
