# Generated by Django 4.1.6 on 2023-02-03 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0002_alter_summary_total_number_of_trades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='total_number_of_winning_trades',
        ),
        migrations.AlterField(
            model_name='summary',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
