# Generated by Django 4.1.6 on 2023-02-09 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_summary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='trading.summary'),
        ),
    ]
