# Generated by Django 4.1.6 on 2023-02-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_summary_total_number_of_winning_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='avg_losing_trade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='summary',
            name='avg_winning_trade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='summary',
            name='largest_losing_trade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='summary',
            name='largest_winning_trade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='summary',
            name='total_number_of_be_trade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='total_number_of_losing_trades',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='total_trade_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='summary',
            name='trade_win_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='closed_position',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
