# Generated by Django 4.1.6 on 2023-02-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_alter_summary_avg_losing_trade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='avg_losing_trade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='summary',
            name='avg_winning_trade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='summary',
            name='largest_losing_trade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='summary',
            name='largest_winning_trade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='summary',
            name='total_trade_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
