# Generated by Django 4.1.6 on 2023-02-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_alter_trade_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='direction',
            field=models.CharField(default='SHORT', max_length=200),
        ),
    ]
