# Generated by Django 4.1.6 on 2023-03-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_trade_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
