# Generated by Django 4.1.6 on 2023-02-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_alter_summary_avg_losing_trade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='trade_win_rate',
            field=models.CharField(max_length=10),
        ),
    ]
