# Generated by Django 4.1.6 on 2023-02-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_alter_summary_trade_win_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='avg_winning_trade',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
