# Generated by Django 4.1.6 on 2023-03-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_alter_summary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
