# Generated by Django 4.1.6 on 2023-02-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_alter_summary_avg_winning_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='starting_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
