# Generated by Django 4.1.6 on 2023-02-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_alter_summary_avg_winning_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='risk_reward',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
