# Generated by Django 4.1.6 on 2023-02-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_alter_summary_avg_winning_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='avg_winning_trade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
