# Generated by Django 4.1.6 on 2023-02-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_alter_summary_avg_winning_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='average_profit_loss_per_trade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='summary',
            name='average_risk_per_trade',
            field=models.CharField(default='1:1', max_length=10),
        ),
        migrations.AddField(
            model_name='summary',
            name='average_risk_reward_per_trade',
            field=models.CharField(default='0%', max_length=10),
        ),
        migrations.AddField(
            model_name='summary',
            name='return_of_investment',
            field=models.CharField(default='0%', max_length=10),
        ),
        migrations.AddField(
            model_name='summary',
            name='total_profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='summary',
            name='trade_win_rate',
            field=models.CharField(max_length=10, verbose_name='0%'),
        ),
    ]
