# Generated by Django 4.1.6 on 2023-02-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_summary_average_profit_loss_per_trade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.summary'),
        ),
    ]
