# Generated by Django 4.1.6 on 2023-02-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_trade_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='average_risk_per_trade',
            field=models.CharField(default='1:1', max_length=200),
        ),
        migrations.AlterField(
            model_name='summary',
            name='average_risk_reward_per_trade',
            field=models.CharField(default='0%', max_length=200),
        ),
        migrations.AlterField(
            model_name='summary',
            name='return_of_investment',
            field=models.CharField(default='0%', max_length=200),
        ),
        migrations.AlterField(
            model_name='summary',
            name='trade_win_rate',
            field=models.CharField(max_length=200, verbose_name='0%'),
        ),
    ]
