# Generated by Django 4.1.6 on 2023-02-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_alter_summary_average_risk_per_trade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
