# Generated by Django 4.1.6 on 2023-02-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0019_alter_summary_average_risk_per_trade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='average_reward_per_trade',
            field=models.CharField(default='0%', max_length=200),
        ),
    ]
