# Generated by Django 4.1.6 on 2023-02-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_summary_average_reward_per_trade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='average_risk_reward_per_trade',
            new_name='average_risk_reward',
        ),
    ]
